version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
  #    volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379", "--protected-mode", "no"]
    container_name: redis-db
  #    environment:
  #      - REDIS_REPLICATION_MODE=master

  mongo:
    image: mongo:5.0.14
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_seed:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    command: nginx -g "daemon off;"
    ports:
      - "3020:3020"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - uploads:/var/lib/docker/volumes/proshop_uploads/_data

    hostname: '127.0.0.1'
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongo_seed:
  uploads:
  certs:

networks:
  redis:
    driver: bridge
