version: '3'
services:
  redis-cache:
    image: redis:alpine
    container_name: redis
    ports: [ "127.0.0.1:6379:6379" ]

  mongo:
    image: mongo:5.0.14
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_seed:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./certs:/home/certs
      - uploads:/var/lib/docker/volumes/proshop_uploads/_data

volumes:
  mongo_seed:
  uploads:
  certs:
