version: '3'
services:
  redis_cache:
    image: redis:alpine
    container_name: redis
    ports: [ "127.0.0.1:6379:6379" ]

  mongo:
    image: mongo:5.0.14
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_seed:/data/db

volumes:
  mongo_seed: