role: ingress
name: main-ingress
namespace: ingress-ns
ingress: true
host: proshop.test
env: production
paths:
  - pathType: Prefix
    path: "/"
    backend:
      service:
        name: client-ext-name
        port:
          number: 80
  - pathType: Prefix
    path: "/api"
    backend:
      service:
        name: server-ext-name
        port:
          number: 80
