selector:
  components: server
role: server
version: v1.5
namespace: server-ns
clusterIp: true
deployment: true
dockerImage: wiseadme/proshop-server
containerPort: 5001
containerCommand: ["npm"]
containerRunArgs:
  - run
  - start
#args: ["GITHUB_TOKEN=$(GITHUB_TOKEN)"]
replicas: 2
limits:
  memory: "500Mi"
  cpu: "5100m"
external:
  name: server-ext-name
  namespace: ingress-ns
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5001
secrets:
  - key: REDIS_URL
    value: ENC[AES256_GCM,data:1+r5eE8VPuei1iKtlLqLD6kohcD1jwcZq1rXdZkTMLcpZN/NnGhKbsK68RkKrl/uZtuPH7Wp,iv:9OTYtWFzD+buDjfua3nKJlTyue7ocIEkmanK3QJPUac=,tag:/aidp9B4bPJrlTi1U7c37Q==,type:str]
  - key: MONGO_URL
    value:
  - key: PORT
    value:
  - key: UPLOADS_DIR
    value:
  - key: REFRESH_TOKEN_SECRET_KEY
    value:
  - key: ACCESS_TOKEN_SECRET_KEY
    value:
  - key: BULLMQ_MAX_CONCURRENCY
    value:
