apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
  namespace: ingress-ns
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: proshop.test
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: client-ext-name
              port:
                number: 80
        - pathType: Prefix
          path: "/api"
          backend:
            service:
              name: server-ext-name
              port:
                number: 80
