{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.role }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range .Values.secrets }}
  {{ .key }}: {{ .value | b64enc }}
  {{- end }}
{{- end }}
