apiVersion: v1
kind: Service
metadata:
  name: database-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
  #      targetPort: 3000
  selector:
    components: database
