version: '3'
services:
  server:
    build: ./packages/server
    command: npm run start
    ports:
      - "5000:5000"
  client:
    build: ./packages/client
    command: npm run start
    ports:
      - "3000:3000"

