import { IProductGatewayService } from '@modules/products/gateway/gateway.service'

export const TYPES = {
    APPLICATION: Symbol.for('App'),
    DB: Symbol.for('DB'),
    REDIS: Symbol.for('REDIS'),
    CONFIG: Symbol.for('CONFIG'),
    CONTROLLERS: {
        IController: Symbol.for('IController'),
    },
    UTILS: {
        ILogger: Symbol.for('ILogger'),
    },
    SERVICES: {
        ICategoryService: Symbol.for('ICategoryService'),
        IProductsService: Symbol.for('IProductsService'),
        IAssetsService: Symbol.for('IAssetsService'),
        IVariantService: Symbol.for('IVariantService'),
        IEventBusService: Symbol.for('IEventBusService'),
        IAttributeService: Symbol.for('IAttributeService'),
        IUnitService: Symbol.for('IUnitService'),
        ICartService: Symbol.for('ICartService'),
        IOrdersService: Symbol.for('IOrdersService'),
        IOptionService: Symbol.for('IOptionService'),
        IUserService: Symbol.for('IUserService'),
        ICustomerService: Symbol.for('ICustomerService'),
        IMetaTagService: Symbol.for('IMetaTagService'),
        IMerchantService: Symbol.for('IMerchantService'),
        ISettingsService: Symbol.for('ISettingsService'),
        ISiteService: Symbol.for('ISiteService'),
        IFilterGroupService: Symbol.for('IFilterGroupService'),
        IFilterItemService: Symbol.for('IFilterItemService'),
    },
    GATEWAYS: {
        IProductGatewayService: Symbol.for('IProductGatewayService'),
        ICartGatewayService: Symbol.for('ICartGatewayService'),
        IOrderGatewayService: Symbol.for('IOrderGatewayService'),
    },
    REPOSITORIES: {
        ICategoryRepository: Symbol.for('ICategoryRepository'),
        IProductsRepository: Symbol.for('IProductsRepository'),
        IAssetsRepository: Symbol.for('IAssetsRepository'),
        IVariantRepository: Symbol.for('IVariantRepository'),
        IAttributeRepository: Symbol.for('IAttributeRepository'),
        IUnitRepository: Symbol.for('IUnitRepository'),
        ICartRepository: Symbol.for('ICartRepository'),
        IOrdersRepository: Symbol.for('IOrdersRepository'),
        IOptionRepository: Symbol.for('IOptionRepository'),
        IUserRepository: Symbol.for('IUserRepository'),
        ICustomerRepository: Symbol.for('ICustomerRepository'),
        IMetaTagRepository: Symbol.for('IMetaTagRepository'),
        IMerchantRepository: Symbol.for('IMerchantRepository'),
        ISettingsRepository: Symbol.for('ISettingsRepository'),
        ISiteRepository: Symbol.for('ISiteRepository'),
        IFilterGroupRepository: Symbol.for('IFilterGroupRepository'),
        IFilterItemRepository: Symbol.for('IFilterItemRepository')
    },
    MIDDLEWARES: {
        IMiddleware: Symbol.for('IMiddleware'),
        ICorsMiddleware: Symbol.for('ICorsMiddleware'),
        IErrorRouteMiddleware: Symbol.for('IErrorRouteMiddleware'),
        IFileLoaderMiddleware: Symbol.for('IFileLoaderMiddleware'),
        ISessionMiddleware: Symbol.for('ISessionMiddleware'),
    },
}
