name: Build server
on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/**'
      - 'packages/admin/**'
      - 'docker-*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.USER }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      ACCESS_TOKEN_SECRET_KEY: ${{ secrets.ACCESS_TOKEN_SECRET_KEY }}
      REFRESH_TOKEN_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      UPLOADS_DIR: ${{ secrets.UPLOADS_DIR }}
    steps:
      - uses: actions/checkout@v3
      - name: server cache modules
        id: server-cache-modules
        uses: actions/cache@v3
        env:
          cache-name: server-cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: install project deps
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
        if: steps.server-cache-modules.outputs.cache-hit != 'true'
      - run: npm run setup
      - name: build projects
        run: npm run build:server
      - name: Log in to Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ secrets.YANDEX_REGISTRY_NAME }}
          username: json_key
          password: ${{ secrets.YANDEX_CLIENT_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/server
          file: ./packages/server/Dockerfile
          push: true
          tags: ${{ secrets.YANDEX_REGISTRY_NAME }}/${{ secrets.YANDEX_REGISTRY_ID }}/${{ secrets.YANDEX_REGISTRY_NAME }}:${{ secrets.SERVER_IMAGE_TAG }}
