name: deploy-client
on:
  push:
    branches: [master]
    paths-ignore:
#      - '.github/**'
      - 'packages/server/**'
#  workflow_run:
#    workflows: ["test"]
#    branches: [master]
#    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache modules
        id: cache-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: install project deps
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm run setup
      - name: build projects
        run: npm run build:client
      - name: Log in to Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ secrets.YR }}
          username: json_key
          password: ${{ secrets.YCR_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/admin
          file: ./packages/admin/Dockerfile
          push: true
          tags: ${{ secrets.YR }}/${{ secrets.YR_ID }}/${{ secrets.YR_NAME }}:${{ secrets.ADMIN_IMAGE_TAG }}

