name: Deploy
on:
  push:
    branches: [master]
  workflow_run:
    workflows: ["test", "build-client", "build-server"]
    branches: [master]
    types: [completed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy id_rsa
        env:
          ID_RSA: ${{ secrets.ID_RSA }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: mkdir .ssh && touch .ssh/id_rsa && printf -- "$ID_RSA" > ~/.ssh/id_rsa
      - name: Login to yandex server
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST"
