name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy id_rsa
        env:
          ID_RSA: ${{ secrets.ID_RSA }}
        run: touch id_rsa && printf -- "$ID_RSA" > id_rsa
      - name: Make id usable
        run: chmod 400 id_rsa
      - name: Login to yandex server
        run: ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      - name: deploy app
        run: cd proshop/ && docker-compose pull && docker-compose up -d
