name: deploy-client
on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/**'
      - 'packages/server/**'
#  workflow_run:
#    workflows: ["test"]
#    branches: [master]
#    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      IMAGE_NAME: ${{ secrets.DOCKER_PROJECT }}
    steps:
      - uses: actions/checkout@v3
      - name: cache modules
        id: cache-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: install project deps
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm run setup
      - name: build projects
        run: npm run build:client
      - name: Build Docker image
        run: docker build . --file packages/admin/Dockerfile --tag cr.yandex/crpjnimru3924065isot/proshop:admin
      - name: Push Docker image to yandex registry
        run: docker push cr.yandex/crpjnimru3924065isot/proshop:admin

