name: Run tests
on:
  pull_request:
    branches: [master, develop]
jobs:
  install_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache project deps
        id: cache-project-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-project-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: install project deps
        if: steps.cache-project-deps.outputs.cache-hit != 'true'
        run: npm run setup
      - name: build project
        run: npm run build

